services:
  - type: web
    name: product-store-server
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production